// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteControl.Rest.Persistence.Database;

#nullable disable

namespace RemoteControl.Rest.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RemoteControl.Rest.Persistence.Database.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Connected")
                        .HasColumnType("bit");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("RemoteControl.Rest.Persistence.Database.Models.DeviceScriptsMapping", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.HasKey("DeviceId", "ScriptId");

                    b.HasIndex("ScriptId");

                    b.ToTable("DeviceScriptsMappings", (string)null);
                });

            modelBuilder.Entity("RemoteControl.Rest.Persistence.Database.Models.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ScriptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scripts", (string)null);
                });

            modelBuilder.Entity("RemoteControl.Rest.Persistence.Database.Models.DeviceScriptsMapping", b =>
                {
                    b.HasOne("RemoteControl.Rest.Persistence.Database.Models.Device", "Device")
                        .WithMany("DeviceScriptsMappings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteControl.Rest.Persistence.Database.Models.Script", "Script")
                        .WithMany("DeviceScriptsMappings")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("RemoteControl.Rest.Persistence.Database.Models.Device", b =>
                {
                    b.Navigation("DeviceScriptsMappings");
                });

            modelBuilder.Entity("RemoteControl.Rest.Persistence.Database.Models.Script", b =>
                {
                    b.Navigation("DeviceScriptsMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
